default_stages: [pre-commit]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.12.2'
    hooks:
      - id: ruff
        args: ['--fix', '--config', 'ruff.toml']
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: ['--unsafe'] # details about the unsafe flag:
        # https://github.com/pre-commit/pre-commit-hooks#check-yaml
        # This is the solution proposed to prevent `check-yaml` from failing on custom tags:
        # https://github.com/pre-commit/pre-commit-hooks/issues/701
      - id: check-added-large-files
        args: ['--enforce-all', '--maxkb', '1000']
        # For the `exclude` argument, see https://pre-commit.com/#regular-expressions
        # Make sure to escape strings correctly to ensure literal matches, for example, using Python
        #
        # >>> print(re.escape("path/to-some/file.ext"))
        # path/to\-some/file\.ext
        #
        # `path/to\-some/file\.ext` is the correct regex pattern to match `path/to-some/file.ext` literally.
        # The inverse operation is more cumbersome: https://stackoverflow.com/a/54840284
        exclude: |
          (?x)^(
            models/.*|
          )$
      - id: check-toml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            models/.*|
          )$
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        exclude: |
          (?x)^(
            models/.*|
          )$
      - id: check-shebang-scripts-are-executable
        exclude: |
          (?x)^(
            models/.*|
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            models/.*|
          )$
      - id: requirements-txt-fixer

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        # Note: to exclude files, uncomment the next line and provide the regex to the associated file or files
        exclude: >
          (?x)^(
            models/.*|
          )$

  # used for checking docstring
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.7
    hooks:
      - id: pydoclint

  # used for static type checking
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright

  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
